---
- name: login as controller
  hosts: controller
  remote_user: root
  become: yes
  tasks:
  - name: install glance
    apt:
      name: glance
      state: present

  - name: update glance-api config file
    ini_file:
      path: /etc/glance/glance-api.conf
      section: "{{ item.section }}"
      option: "{{ item.option }}"
      value: "{{ item.value }}"
    with_items:
      - { section: "database", option: "connection", value: "mysql+pymysql://glance:root@controller/glance" }
      - { section: "keystone_authtoken", option: "auth_uri", value: "http://controller:5000"}
      - { section: "keystone_authtoken", option: "auth_url", value: "http://controller:5000"}
      - { section: "keystone_authtoken", option: "memcached_servers", value: "controller:11211"}
      - { section: "keystone_authtoken", option: "auth_type", value: "password"}
      - { section: "keystone_authtoken", option: "project_domain_name", value: "Default"}
      - { section: "keystone_authtoken", option: "user_domain_name", value: "Default"}
      - { section: "keystone_authtoken", option: "project_name", value: "service"}
      - { section: "keystone_authtoken", option: "username", value: "glance"}
      - { section: "keystone_authtoken", option: "password", value: "root"}
      - { section: "paste_deploy", option: "flavor", value: "keystone"}
      - { section: "glance_store", option: "stores", value: "file,http"}
      - { section: "glance_store", option: "default_store", value: "file"}
      - { section: "glance_store", option: "filesystem_store_datadir", value: "/var/lib/glance/images/"}


  - name: update glance-registryneutron-l3-agent config file
    ini_file:
        path: /etc/glance/glance-registry.conf
        section: "{{ item.section }}"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
    with_items:
      - { section: "database", option: "connection", value: "mysql+pymysql://glance:root@controller/glance" }
      - { section: "keystone_authtoken", option: "auth_uri", value: "http://controller:5000"}
      - { section: "keystone_authtoken", option: "auth_url", value: "http://controller:5000"}
      - { section: "keystone_authtoken", option: "memcached_servers", value: "controller:11211"}
      - { section: "keystone_authtoken", option: "auth_type", value: "password"}
      - { section: "keystone_authtoken", option: "project_domain_name", value: "Default"}
      - { section: "keystone_authtoken", option: "user_domain_name", value: "Default"}
      - { section: "keystone_authtoken", option: "project_name", value: "service"}
      - { section: "keystone_authtoken", option: "username", value: "glance"}
      - { section: "keystone_authtoken", option: "password", value: "root"}
      - { section: "paste_deploy", option: "flavor", value: "keystone"}

  - name: db sync glance
    shell: su -s /bin/sh -c "glance-manage db_sync" glance

  - name: glance services status
    service: name={{item}} state=restarted
    with_items:
      - glance-registry
      - glance-api

  - name: install images
    shell: "{{ item }}"
    with_items:
#      - ". /root/admin-openrc.sh"
#      - "wget http://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-disk.img"
      - "sh glance-verification.sh"
      - "openstack image create cirros --file cirros-0.4.0-x86_64-disk.img --disk-format qcow2 --container-format bare --public"
#      - "openstack image list"
