---
- name: login as controller
  hosts: controller
  remote_user: root
  become: yes
  vars:
    mysql_root_pass: root
  tasks:
  - name: install neturon packages
    apt:
      name: "{{ item }}" 
      state: present
    with_items:
      - neutron-server
      - neutron-plugin-ml2
      - neutron-linuxbridge-agent
      - neutron-l3-agent
      - neutron-dhcp-agent
      - neutron-metadata-agent

  - name: update neutron config file
    ini_file:
      path: /etc/neutron/neutron.conf
      section: "{{ item.section }}"
      option: "{{ item.option }}"
      value: "{{ item.value }}"
    with_items:
      - { section: "database", option: "connection", value: "mysql+pymysql://neutron:root@controller/neutron" }
      - { section: "DEFAULT", option: "core_plugin", value: "ml2" }
      - { section: "DEFAULT", option: "service_plugins", value: "router" }
      - { section: "DEFAULT", option: "allow_overlapping_ips", value: "true" }
      - { section: "DEFAULT", option: "transport_url", value: "rabbit://openstack:root@controller" }
      - { section: "DEFAULT", option: "auth_strategy", value: "keystone" }
      - { section: "keystone_authtoken", option: "auth_uri", value: "http://controller:5000" }
      - { section: "keystone_authtoken", option: "auth_url", value: "http://controller:5000" }
      - { section: "keystone_authtoken", option: "memcached_servers", value: "controller:11211" }
      - { section: "keystone_authtoken", option: "auth_type", value: "password" }
      - { section: "keystone_authtoken", option: "project_domain_name", value: "default" }
      - { section: "keystone_authtoken", option: "user_domain_name", value: "default" }
      - { section: "keystone_authtoken", option: "project_name", value: "service" }
      - { section: "keystone_authtoken", option: "username", value: "neutron" }
      - { section: "keystone_authtoken", option: "password", value: "root" } 
      - { section: "DEFAULT", option: "notify_nova_on_port_status_changes", value: "true" }
      - { section: "DEFAULT", option: "notify_nova_on_port_data_changes", value: "true" }
      - { section: "nova", option: "auth_url", value: "http://controller:5000" }
      - { section: "nova", option: "auth_type", value: "password" }
      - { section: "nova", option: "project_domain_name", value: "default" }
      - { section: "nova", option: "user_domain_name", value: "default" }
      - { section: "nova", option: "region_name", value: "password" }
      - { section: "nova", option: "project_name", value: "service" }
      - { section: "nova", option: "username", value: "nova" }
      - { section: "nova", option: "password", value: "root" }
      - { section: "oslo_concurrency", option: "lock_path", value: "/var/lib/neutron/tmp" } 

  - name: update ml2_conf config file
    ini_file:
      path: /etc/neutron/plugins/ml2/ml2_conf.ini
      section: "{{ item.section }}"
      option: "{{ item.option }}"
      value: "{{ item.value }}"
    with_items:
      - { section: "ml2", option: "type_drivers", value: "flat,vlan,vxlan" }
      - { section: "ml2", option: "tenant_network_types", value: "vxlan" }
      - { section: "ml2", option: "mechanism_drivers", value: "linuxbridge,l2population" }
      - { section: "ml2", option: "extension_drivers", value: "port_security" }
      - { section: "ml2_type_flat", option: "flat_networks", value: "provider" }
      - { section: "ml2_type_vxlan", option: "vni_ranges", value: "1:1000" }
      - { section: "securitygroup", option: "enable_ipset", value: "true" }

  - name: update linuxbridge_agent config file
    ini_file:
      path: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
      section: "{{ item.section }}"
      option: "{{ item.option }}"
      value: "{{ item.value }}"
    with_items:
      - { section: "linux_bridge", option: "physical_interface_mappings", value: "provider:enp0s3" }
      - { section: "vxlan", option: "enable_vxlan", value: "true" }
      - { section: "vxlan", option: "local_ip", value: "10.0.0.11" }
      - { section: "vxlan", option: "l2_population", value: "true" }
      - { section: "securitygroup", option: "enable_security_group", value: "true" }
      - { section: "securitygroup", option: "firewall_driver", value: "neutron.agent.linux.iptables_firewall.IptablesFirewallDriver" }

  - name: update l3_agent config file
    ini_file:
      path: /etc/neutron/l3_agent.ini
      section: "{{ item.section }}"
      option: "{{ item.option }}"
      value: "{{ item.value }}"
    with_items:
      - { section: "DEFAULT", option: "interface_driver", value: "linuxbridge" }

  - name: update dhcp_agent config file
    ini_file:
      path: /etc/neutron/dhcp_agent.ini
      section: "{{ item.section }}"
      option: "{{ item.option }}"
      value: "{{ item.value }}"
    with_items:
      - { section: "DEFAULT", option: "interface_driver", value: "linuxbridge" }
      - { section: "DEFAULT", option: "dhcp_driver", value: "neutron.agent.linux.dhcp.Dnsmasq" }
      - { section: "DEFAULT", option: "enable_isolated_metadata", value: "true" }

  - name: update metadata_agent config file
    ini_file:
      path: /etc/neutron/metadata_agent.ini
      section: "{{ item.section }}"
      option: "{{ item.option }}"
      value: "{{ item.value }}"
    with_items:
      - { section: "DEFAULT", option: "nova_metadata_host", value: "controller" }
      - { section: "DEFAULT", option: "metadata_proxy_shared_secret", value: "root" }

  - name: update nova config file
    ini_file:
      path: /etc/nova/nova.conf
      section: "{{ item.section }}"
      option: "{{ item.option }}"
      value: "{{ item.value }}"
    with_items:
      - { section: "neutron", option: "url", value: "http://controller:9696" }
      - { section: "neutron", option: "auth_url", value: "http://controller:5000" }
      - { section: "neutron", option: "auth_type", value: "password" }
      - { section: "neutron", option: "project_domain_name", value: "default" }
      - { section: "neutron", option: "user_domain_name", value: "default" }
      - { section: "neutron", option: "region_name", value: "RegionOne" }
      - { section: "neutron", option: "project_name", value: "service" }
      - { section: "neutron", option: "username", value: "neutron" }
      - { section: "neutron", option: "password", value: "root" }
      - { section: "neutron", option: "service_metadata_proxy", value: "true" }
      - { section: "neutron", option: "metadata_proxy_shared_secret", value: "root" }

  - name: db sync neturon
    shell: su -s /bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head" neutron
#    ignore_errors: yes

  - name: restart services
    service:
      name: "{{ item }}" 
      state: restarted
    with_items:
      - "nova-api"
      - "neutron-server"
      - "neutron-linuxbridge-agent"
      - "neutron-dhcp-agent"
      - "neutron-metadata-agent"
      - "neutron-l3-agent"

- name: login as compute
  hosts: compute
  remote_user: root
  become: yes
  tasks:
    - name: install neutron-linuxbridge
      apt:
        name: neutron-linuxbridge-agent
        state: present

    - name: update neutron config file
      ini_file:
        path:  /etc/neutron/neutron.conf
        section: "{{ item.section }}"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      with_items:
        - { section: "DEFAULT", option: "transport_url", value: "rabbit://openstack:root@controller" }
        - { section: "DEFAULT", option: "auth_strategy", value: "keystone" }
        - { section: "keystone_authtoken", option: "auth_uri", value: "http://controller:5000"}
        - { section: "keystone_authtoken", option: "auth_url", value: "http://controller:5000"}
        - { section: "keystone_authtoken", option: "memcached_servers", value: "controller:11211"}
        - { section: "keystone_authtoken", option: "auth_type", value: "password"}
        - { section: "keystone_authtoken", option: "project_domain_name", value: "default"}
        - { section: "keystone_authtoken", option: "user_domain_name", value: "default"}
        - { section: "keystone_authtoken", option: "project_name", value: "service"}
        - { section: "keystone_authtoken", option: "username", value: "neutron"}
        - { section: "keystone_authtoken", option: "password", value: "root"}
        - { section: "oslo_concurrency", option: "lock_path", value: "/var/lib/neutron/tmp"}

    - name: update linuxbridge_agent config file
      ini_file:
        path: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
        section: "{{ item.section }}"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      with_items:
        - { section: "linux_bridge", option: "physical_interface_mappings", value: "provider:enp0s3" }
        - { section: "vxlan", option: "enable_vxlan", value: "true" }
        - { section: "vxlan", option: "local_ip", value: "10.0.0.31"}
        - { section: "vxlan", option: "l2_population", value: "true"}
        - { section: "securitygroup", option: "enable_security_group", value: "true"}
        - { section: "securitygroup", option: "firewall_driver", value: "neutron.agent.linux.iptables_firewall.IptablesFirewallDriver"}

    - name: update nova config file
      ini_file:
        path: /etc/nova/nova.conf
        section: "{{ item.section }}"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      with_items:
        - { section: "neutron", option: "url", value: "http://controller:9696"}
        - { section: "neutron", option: "auth_url", value: "http://controller:5000"}
        - { section: "neutron", option: "auth_type", value: "password"}
        - { section: "neutron", option: "project_domain_name", value: "default"}
        - { section: "neutron", option: "user_domain_name", value: "default"}
        - { section: "neutron", option: "region_name", value: "RegionOne"}
        - { section: "neutron", option: "project_name", value: "service"}
        - { section: "neutron", option: "username", value: "neutron"}
        - { section: "neutron", option: "password", value: "root"}


    - name: nova services status
      service: 
        name: "{{ item }}" 
        state: restarted
      with_items:
        - "nova-compute"
        - "neutron-linuxbridge-agent"

- name: login as controller
  hosts: controller
  remote_user: root
  become: yes
  tasks:
    - name: launch of the neutron agents
      shell: "{{ item }}"
      with_items:
        - "sh neutron-verification.sh"
#        - "openstack network agent list"
